
-- 시스템 계정으로 로그인 후 예) SESSION
-- CONNECT system / oracle
CREATE USER hyokwan
IDENTIFIED BY hyokwan

-- 권한부여
-- RESOURCE 자원
-- DBA (CRUD 권한등 DB 관리자 권한 부여)
-- CONNECT 접속 권한
GRANT RESOURCE, DBA, CONNECT TO hyokwan

-- 사용자 계정으로 로그인 후 예) SESSION
-- CONNECT hyokwan / hyokwan

-- CRUD (CREATE)
-- SQL~!!!CRUD  C(CREATE) 
CREATE TABLE KOPO_PRODUCT_VOLUME
(
    REGIONID VARCHAR2(2),
    PRODUCTGROUP VARCHAR2(100),
    YEARWEEK VARCHAR2(6),
    VOLUME NUMBER
)

--CRUD [R] READ 데이터 조회
SELECT *
FROM KOPO_PRODUCT_VOLUME

--CRUD [U] 데이터 삽입/수정
-- REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME

INSERT INTO KOPO_PRODUCT_VOLUME 
VALUES ( 'A2','하나A카드','202405', 1000)

INSERT INTO KOPO_PRODUCT_VOLUME 
(REGIONID, PRODUCTGROUP)   
VALUES ( 'A9','하나C카드')

--CRUD [U] 데이터 삽입/수정
-- REGIONID, PRODUCTGROUP, YEARWEEK, VOLUME

UPDATE KOPO_PRODUCT_VOLUME
SET YEARWEEK = '202505'
WHERE REGIONID = 'A9'

-- CRUD DELETE (삭제)
DELETE FROM KOPO_PRODUCT_VOLUME
WHERE REGIONID = 'A9'




